
# Generated by CodiumAI
from GitHub_Copilot.String_Sorted_Unittests import ginorts


import pytest

class TestGinorts:

    # Given a string with only lowercase letters, the function should return the same string sorted alphabetically.
    def test_lowercase_letters(self):
        input_string = "cba"
        expected_output = "abc"
        assert ginorts(input_string) == expected_output

    # Given a string with only uppercase letters, the function should return the same string sorted alphabetically.
    def test_uppercase_letters(self):
        input_string = "CBA"
        expected_output = "ABC"
        assert ginorts(input_string) == expected_output

    # Given a string with only odd digits, the function should return the same string sorted ascending.
    def test_odd_digits(self):
        input_string = "753"
        expected_output = "357"
        assert ginorts(input_string) == expected_output

    # Given an empty string, the function should return an empty string.
    def test_empty_string(self):
        input_string = ""
        expected_output = ""
        assert ginorts(input_string) == expected_output

    # Given a string with no lowercase letters, the function should return the string sorted with uppercase letters first, followed by digits.
    def test_no_lowercase_letters(self):
        input_string = "ABC123"
        expected_output = "ABC132"
        assert ginorts(input_string) == expected_output

    # Given a string with no uppercase letters, the function should return the string sorted with lowercase letters first, followed by digits.
    def test_no_uppercase_letters(self):
        input_string = "abc123"
        expected_output = "abc123"
        assert ginorts(input_string) == expected_output